-- ─────────────────────────────────────────────────────────────────────────────
-- PetBorder — Breeds reference table
-- Static reference data for the breed combobox.
-- Public read (no auth required). Updated by admins only.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.breeds (
  id          uuid primary key default uuid_generate_v4(),
  pet_type    text not null check (pet_type in ('dog', 'cat')),
  name        text not null,
  banned      boolean not null default false,
  banned_note text,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now(),
  constraint breeds_unique_name_type unique (pet_type, name)
);

comment on table public.breeds is
  'Reference list of recognised dog and cat breeds for the combobox. '
  'Banned breeds are included so the UI can show a warning.';

-- Public read — no auth required (reference data)
alter table public.breeds enable row level security;

create policy "Public can read breeds"
  on public.breeds for select
  using (true);

-- Index for fast filtered lookups
create index if not exists breeds_pet_type_idx on public.breeds (pet_type, sort_order);

-- ─────────────────────────────────────────────────────────────────────────────
-- Seed data — Dog breeds (162 entries, alphabetical)
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.breeds (pet_type, name, banned, banned_note, sort_order) values
  ('dog', 'Affenpinscher', false, null, 10),
  ('dog', 'Afghan Hound', false, null, 20),
  ('dog', 'Airedale Terrier', false, null, 30),
  ('dog', 'Akita', false, null, 40),
  ('dog', 'Alaskan Klee Kai', false, null, 50),
  ('dog', 'Alaskan Malamute', false, null, 60),
  ('dog', 'American Bulldog', false, null, 70),
  ('dog', 'American English Coonhound', false, null, 80),
  ('dog', 'American Eskimo Dog', false, null, 90),
  ('dog', 'American Foxhound', false, null, 100),
  ('dog', 'American Hairless Terrier', false, null, 110),
  ('dog', 'American Staffordshire Terrier', false, null, 120),
  ('dog', 'American Water Spaniel', false, null, 130),
  ('dog', 'Anatolian Shepherd Dog', false, null, 140),
  ('dog', 'Australian Cattle Dog', false, null, 150),
  ('dog', 'Australian Shepherd', false, null, 160),
  ('dog', 'Australian Terrier', false, null, 170),
  ('dog', 'Azawakh', false, null, 180),
  ('dog', 'Barbet', false, null, 190),
  ('dog', 'Basenji', false, null, 200),
  ('dog', 'Basset Hound', false, null, 210),
  ('dog', 'Beagle', false, null, 220),
  ('dog', 'Bearded Collie', false, null, 230),
  ('dog', 'Bedlington Terrier', false, null, 240),
  ('dog', 'Belgian Malinois', false, null, 250),
  ('dog', 'Belgian Sheepdog', false, null, 260),
  ('dog', 'Belgian Tervuren', false, null, 270),
  ('dog', 'Bergamasco Sheepdog', false, null, 280),
  ('dog', 'Berger Picard', false, null, 290),
  ('dog', 'Bernese Mountain Dog', false, null, 300),
  ('dog', 'Bichon Frise', false, null, 310),
  ('dog', 'Biewer Terrier', false, null, 320),
  ('dog', 'Black and Tan Coonhound', false, null, 330),
  ('dog', 'Black Russian Terrier', false, null, 340),
  ('dog', 'Bloodhound', false, null, 350),
  ('dog', 'Bluetick Coonhound', false, null, 360),
  ('dog', 'Boerboel', false, null, 370),
  ('dog', 'Border Collie', false, null, 380),
  ('dog', 'Border Terrier', false, null, 390),
  ('dog', 'Borzoi', false, null, 400),
  ('dog', 'Boston Terrier', false, null, 410),
  ('dog', 'Bouvier des Flandres', false, null, 420),
  ('dog', 'Boxer', false, null, 430),
  ('dog', 'Boykin Spaniel', false, null, 440),
  ('dog', 'Briard', false, null, 450),
  ('dog', 'Brittany', false, null, 460),
  ('dog', 'Brussels Griffon', false, null, 470),
  ('dog', 'Bull Terrier', false, null, 480),
  ('dog', 'Bulldog', false, null, 490),
  ('dog', 'Bullmastiff', false, null, 500),
  ('dog', 'Cairn Terrier', false, null, 510),
  ('dog', 'Canaan Dog', false, null, 520),
  ('dog', 'Cane Corso', false, null, 530),
  ('dog', 'Cardigan Welsh Corgi', false, null, 540),
  ('dog', 'Caucasian Shepherd Dog', false, null, 550),
  ('dog', 'Cavalier King Charles Spaniel', false, null, 560),
  ('dog', 'Cesky Terrier', false, null, 570),
  ('dog', 'Chesapeake Bay Retriever', false, null, 580),
  ('dog', 'Chihuahua', false, null, 590),
  ('dog', 'Chinese Crested', false, null, 600),
  ('dog', 'Chinese Shar-Pei', false, null, 610),
  ('dog', 'Chow Chow', false, null, 620),
  ('dog', 'Cirneco dell''Etna', false, null, 630),
  ('dog', 'Clumber Spaniel', false, null, 640),
  ('dog', 'Cocker Spaniel', false, null, 650),
  ('dog', 'Collie', false, null, 660),
  ('dog', 'Coton de Tulear', false, null, 670),
  ('dog', 'Curly-Coated Retriever', false, null, 680),
  ('dog', 'Dachshund', false, null, 690),
  ('dog', 'Dalmatian', false, null, 700),
  ('dog', 'Dandie Dinmont Terrier', false, null, 710),
  ('dog', 'Dobermann', false, null, 720),
  ('dog', 'Dogo Argentino', true, 'Banned under Australian biosecurity law — cannot be imported.', 730),
  ('dog', 'Dutch Shepherd', false, null, 740),
  ('dog', 'English Cocker Spaniel', false, null, 750),
  ('dog', 'English Foxhound', false, null, 760),
  ('dog', 'English Setter', false, null, 770),
  ('dog', 'English Springer Spaniel', false, null, 780),
  ('dog', 'English Toy Spaniel', false, null, 790),
  ('dog', 'Entlebucher Mountain Dog', false, null, 800),
  ('dog', 'Field Spaniel', false, null, 810),
  ('dog', 'Fila Brasileiro', true, 'Banned under Australian biosecurity law — cannot be imported.', 820),
  ('dog', 'Finnish Lapphund', false, null, 830),
  ('dog', 'Finnish Spitz', false, null, 840),
  ('dog', 'Flat-Coated Retriever', false, null, 850),
  ('dog', 'French Bulldog', false, null, 860),
  ('dog', 'German Pinscher', false, null, 870),
  ('dog', 'German Shepherd', false, null, 880),
  ('dog', 'German Shorthaired Pointer', false, null, 890),
  ('dog', 'German Wirehaired Pointer', false, null, 900),
  ('dog', 'Giant Schnauzer', false, null, 910),
  ('dog', 'Glen of Imaal Terrier', false, null, 920),
  ('dog', 'Golden Retriever', false, null, 930),
  ('dog', 'Gordon Setter', false, null, 940),
  ('dog', 'Great Dane', false, null, 950),
  ('dog', 'Great Pyrenees', false, null, 960),
  ('dog', 'Greater Swiss Mountain Dog', false, null, 970),
  ('dog', 'Greyhound', false, null, 980),
  ('dog', 'Harrier', false, null, 990),
  ('dog', 'Havanese', false, null, 1000),
  ('dog', 'Hovawart', false, null, 1010),
  ('dog', 'Ibizan Hound', false, null, 1020),
  ('dog', 'Icelandic Sheepdog', false, null, 1030),
  ('dog', 'Irish Red and White Setter', false, null, 1040),
  ('dog', 'Irish Setter', false, null, 1050),
  ('dog', 'Irish Terrier', false, null, 1060),
  ('dog', 'Irish Water Spaniel', false, null, 1070),
  ('dog', 'Irish Wolfhound', false, null, 1080),
  ('dog', 'Italian Greyhound', false, null, 1090),
  ('dog', 'Jack Russell Terrier', false, null, 1100),
  ('dog', 'Japanese Tosa', true, 'Banned under Australian biosecurity law — cannot be imported.', 1110),
  ('dog', 'Keeshond', false, null, 1120),
  ('dog', 'Kerry Blue Terrier', false, null, 1130),
  ('dog', 'Komondor', false, null, 1140),
  ('dog', 'Kooikerhondje', false, null, 1150),
  ('dog', 'Kuvasz', false, null, 1160),
  ('dog', 'Labrador Retriever', false, null, 1170),
  ('dog', 'Lagotto Romagnolo', false, null, 1180),
  ('dog', 'Lakeland Terrier', false, null, 1190),
  ('dog', 'Lancashire Heeler', false, null, 1200),
  ('dog', 'Leonberger', false, null, 1210),
  ('dog', 'Lhasa Apso', false, null, 1220),
  ('dog', 'Lowchen', false, null, 1230),
  ('dog', 'Maltese', false, null, 1240),
  ('dog', 'Manchester Terrier', false, null, 1250),
  ('dog', 'Mastiff', false, null, 1260),
  ('dog', 'Miniature Bull Terrier', false, null, 1270),
  ('dog', 'Miniature Pinscher', false, null, 1280),
  ('dog', 'Miniature Schnauzer', false, null, 1290),
  ('dog', 'Mudi', false, null, 1300),
  ('dog', 'Neapolitan Mastiff', false, null, 1310),
  ('dog', 'Newfoundland', false, null, 1320),
  ('dog', 'Norfolk Terrier', false, null, 1330),
  ('dog', 'Norwegian Buhund', false, null, 1340),
  ('dog', 'Norwegian Elkhound', false, null, 1350),
  ('dog', 'Norwegian Lundehund', false, null, 1360),
  ('dog', 'Norwich Terrier', false, null, 1370),
  ('dog', 'Nova Scotia Duck Tolling Retriever', false, null, 1380),
  ('dog', 'Old English Sheepdog', false, null, 1390),
  ('dog', 'Otterhound', false, null, 1400),
  ('dog', 'Papillon', false, null, 1410),
  ('dog', 'Parson Russell Terrier', false, null, 1420),
  ('dog', 'Pekingese', false, null, 1430),
  ('dog', 'Pembroke Welsh Corgi', false, null, 1440),
  ('dog', 'Perro de Presa Canario', true, 'Banned under Australian biosecurity law — cannot be imported.', 1450),
  ('dog', 'Petit Basset Griffon Vendeen', false, null, 1460),
  ('dog', 'Pharaoh Hound', false, null, 1470),
  ('dog', 'Plott Hound', false, null, 1480),
  ('dog', 'Pointer', false, null, 1490),
  ('dog', 'Polish Lowland Sheepdog', false, null, 1500),
  ('dog', 'Pomeranian', false, null, 1510),
  ('dog', 'Poodle (Miniature)', false, null, 1520),
  ('dog', 'Poodle (Standard)', false, null, 1530),
  ('dog', 'Poodle (Toy)', false, null, 1540),
  ('dog', 'Portuguese Podengo', false, null, 1550),
  ('dog', 'Portuguese Water Dog', false, null, 1560),
  ('dog', 'Pug', false, null, 1570),
  ('dog', 'Puli', false, null, 1580),
  ('dog', 'Pumi', false, null, 1590),
  ('dog', 'Pyrenean Shepherd', false, null, 1600),
  ('dog', 'Rat Terrier', false, null, 1610),
  ('dog', 'Redbone Coonhound', false, null, 1620),
  ('dog', 'Rhodesian Ridgeback', false, null, 1630),
  ('dog', 'Rottweiler', false, null, 1640),
  ('dog', 'Russell Terrier', false, null, 1650),
  ('dog', 'Saint Bernard', false, null, 1660),
  ('dog', 'Saluki', false, null, 1670),
  ('dog', 'Samoyed', false, null, 1680),
  ('dog', 'Schipperke', false, null, 1690),
  ('dog', 'Scottish Deerhound', false, null, 1700),
  ('dog', 'Scottish Terrier', false, null, 1710),
  ('dog', 'Sealyham Terrier', false, null, 1720),
  ('dog', 'Shetland Sheepdog', false, null, 1730),
  ('dog', 'Shiba Inu', false, null, 1740),
  ('dog', 'Shih Tzu', false, null, 1750),
  ('dog', 'Siberian Husky', false, null, 1760),
  ('dog', 'Silky Terrier', false, null, 1770),
  ('dog', 'Skye Terrier', false, null, 1780),
  ('dog', 'Sloughi', false, null, 1790),
  ('dog', 'Smooth Fox Terrier', false, null, 1800),
  ('dog', 'Spanish Water Dog', false, null, 1810),
  ('dog', 'Spinone Italiano', false, null, 1820),
  ('dog', 'Staffordshire Bull Terrier', false, null, 1830),
  ('dog', 'Standard Schnauzer', false, null, 1840),
  ('dog', 'Sussex Spaniel', false, null, 1850),
  ('dog', 'Swedish Lapphund', false, null, 1860),
  ('dog', 'Swedish Vallhund', false, null, 1870),
  ('dog', 'Tibetan Mastiff', false, null, 1880),
  ('dog', 'Tibetan Spaniel', false, null, 1890),
  ('dog', 'Tibetan Terrier', false, null, 1900),
  ('dog', 'Toy Fox Terrier', false, null, 1910),
  ('dog', 'Treeing Walker Coonhound', false, null, 1920),
  ('dog', 'Vizsla', false, null, 1930),
  ('dog', 'Weimaraner', false, null, 1940),
  ('dog', 'Welsh Springer Spaniel', false, null, 1950),
  ('dog', 'Welsh Terrier', false, null, 1960),
  ('dog', 'West Highland White Terrier', false, null, 1970),
  ('dog', 'Whippet', false, null, 1980),
  ('dog', 'Wire Fox Terrier', false, null, 1990),
  ('dog', 'Wirehaired Pointing Griffon', false, null, 2000),
  ('dog', 'Wirehaired Vizsla', false, null, 2010),
  ('dog', 'Xoloitzcuintli', false, null, 2020),
  ('dog', 'Yorkshire Terrier', false, null, 2030),
  ('dog', 'Mixed breed / Crossbreed', false, null, 9990)
on conflict (pet_type, name) do update
  set banned = excluded.banned,
      banned_note = excluded.banned_note,
      sort_order = excluded.sort_order;

-- ─────────────────────────────────────────────────────────────────────────────
-- Seed data — Cat breeds (67 entries, alphabetical)
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.breeds (pet_type, name, banned, banned_note, sort_order) values
  ('cat', 'Abyssinian', false, null, 10),
  ('cat', 'American Bobtail', false, null, 20),
  ('cat', 'American Curl', false, null, 30),
  ('cat', 'American Shorthair', false, null, 40),
  ('cat', 'American Wirehair', false, null, 50),
  ('cat', 'Australian Mist', false, null, 60),
  ('cat', 'Balinese', false, null, 70),
  ('cat', 'Bengal', true, 'Banned from import to Australia as of March 2026 — DAFF regulation.', 80),
  ('cat', 'Birman', false, null, 90),
  ('cat', 'Bombay', false, null, 100),
  ('cat', 'British Longhair', false, null, 110),
  ('cat', 'British Shorthair', false, null, 120),
  ('cat', 'Burmese', false, null, 130),
  ('cat', 'Burmilla', false, null, 140),
  ('cat', 'Chartreux', false, null, 150),
  ('cat', 'Chausie', false, null, 160),
  ('cat', 'Colorpoint Shorthair', false, null, 170),
  ('cat', 'Cornish Rex', false, null, 180),
  ('cat', 'Cymric', false, null, 190),
  ('cat', 'Devon Rex', false, null, 200),
  ('cat', 'Donskoy / Don Sphynx', false, null, 210),
  ('cat', 'Egyptian Mau', false, null, 220),
  ('cat', 'European Shorthair', false, null, 230),
  ('cat', 'Exotic Shorthair', false, null, 240),
  ('cat', 'Havana Brown', false, null, 250),
  ('cat', 'Highlander', false, null, 260),
  ('cat', 'Himalayan', false, null, 270),
  ('cat', 'Japanese Bobtail', false, null, 280),
  ('cat', 'Javanese', false, null, 290),
  ('cat', 'Khao Manee', false, null, 300),
  ('cat', 'Korat', false, null, 310),
  ('cat', 'Kurilian Bobtail', false, null, 320),
  ('cat', 'LaPerm', false, null, 330),
  ('cat', 'Lykoi', false, null, 340),
  ('cat', 'Maine Coon', false, null, 350),
  ('cat', 'Manx', false, null, 360),
  ('cat', 'Munchkin', false, null, 370),
  ('cat', 'Nebelung', false, null, 380),
  ('cat', 'Norwegian Forest Cat', false, null, 390),
  ('cat', 'Ocicat', false, null, 400),
  ('cat', 'Oriental Longhair', false, null, 410),
  ('cat', 'Oriental Shorthair', false, null, 420),
  ('cat', 'Persian', false, null, 430),
  ('cat', 'Peterbald', false, null, 440),
  ('cat', 'Pixie-bob', false, null, 450),
  ('cat', 'Ragamuffin', false, null, 460),
  ('cat', 'Ragdoll', false, null, 470),
  ('cat', 'Russian Blue', false, null, 480),
  ('cat', 'Savannah', true, 'Hybrid species — cannot enter Australia under DAFF biosecurity law.', 490),
  ('cat', 'Scottish Fold', false, null, 500),
  ('cat', 'Scottish Straight', false, null, 510),
  ('cat', 'Selkirk Rex', false, null, 520),
  ('cat', 'Serengeti', false, null, 530),
  ('cat', 'Siamese', false, null, 540),
  ('cat', 'Siberian', false, null, 550),
  ('cat', 'Singapura', false, null, 560),
  ('cat', 'Snowshoe', false, null, 570),
  ('cat', 'Sokoke', false, null, 580),
  ('cat', 'Somali', false, null, 590),
  ('cat', 'Sphynx', false, null, 600),
  ('cat', 'Thai', false, null, 610),
  ('cat', 'Tonkinese', false, null, 620),
  ('cat', 'Toyger', false, null, 630),
  ('cat', 'Turkish Angora', false, null, 640),
  ('cat', 'Turkish Van', false, null, 650),
  ('cat', 'Domestic Shorthair', false, null, 9960),
  ('cat', 'Domestic Longhair', false, null, 9970),
  ('cat', 'Domestic Mediumhair', false, null, 9980),
  ('cat', 'Mixed breed', false, null, 9990)
on conflict (pet_type, name) do update
  set banned = excluded.banned,
      banned_note = excluded.banned_note,
      sort_order = excluded.sort_order;
